version: '3.8'

services:
  # Nginx Web Server
  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "80:80"
    restart: always
    depends_on:
      - db
    networks:
      - app_network

  # PostgreSQL Database
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app_network

# Define a custom network for the services
networks:
  app_network:
    driver: bridge

# Define a volume for PostgreSQL data persistence
volumes:
  postgres_data:
